AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ServelessFunction:
    Properties:
      CodeUri: s3://seon-virginia-01/13ff088c158d7bb6b56b1d2ca94a99c8
      Environment:
        Variables:
          S3_BUCKET: s3://seon-virginia-01
      FunctionName: workshop-translate-20
      Handler: com.amazonaws.lambda.LambdaTranslateHandler::handleRequest
      MemorySize: 1024
      Role: arn:aws:iam::550622896891:role/Alexa-DevOps-Role
      Runtime: java8
      Tags:
        ContactTag: workshop-translte
      Timeout: 30
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
